services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_ENCRYPTION_KEY=e77e65c44edf9b99afb2ef9796eb731e
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_DISABLE_PRODUCTION_MAIN_PROCESS=false
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n_password
    volumes:
      - n8n_data:/home/node/.n8n
      - ./llm:/app/llm
      - ./api:/app/api
    depends_on:
      - postgres
      - prompt-manager
    extra_hosts:
      - "host.docker.internal:host-gateway"

  prompt-manager:
    image: python:3.11-slim
    container_name: prompt-manager
    restart: unless-stopped
    ports:
      - "8001:8001"
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./api:/app/api
      - ./llm:/app/llm
    command: >
      sh -c "pip install fastapi uvicorn &&
             python api/prompt_manager.py"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: n8n-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  n8n_data:
  postgres_data:
